### ISSUE TITLE
Document Prevalence Period Changes

### ISSUE THREAD

**Issue by aeyates** [OHSUCMP/htnu18ig#114]
Matt recently made changes to separate the logic for encounter-diagnosis and problem-list-item conditions. As part of that effort, Encounter Conditions of **Hypertension** no longer consider time and also do not consider the clinical status. This means that an encounter from 10 years ago where the clinical status is “resolved” and the condition is considered abated will still be considered a “Preexisting Diagnosis of Hypertension” and move through the workflow. If the condition is on the Problem List, the clinical status and prevalence period are considered when deciding whether it’s active.
 
I can see an argument for both implementations, but it does seem a little inconsistent to be strict in one case and more lax in the other. For the other conditions we consider (End Stage Renal Disease and Pregnancy) we use time and clinical status for both condition categories. I wasn’t around when this was requested, so don’t know the background. If it’s as intended, that’s great, but a little context would help so I can update the documentation.

**Comment by mattStorer** [comment]
the context around this relates to the Prevalence Period, and that many Conditions that should have been showing up, were not.  this has to do with the existence (or rather lack thereof) of clinicalStatus, onset, and abatement elements on the associated Condition resources.  previously, it was assumed that some of these must exist with logic to handle some missing elements, but in fact many such resources coming from Epic do not contain any of them.

as such, the "Prevalence Period" (which returned an Interval) was replaced with a new definition "Is Valid Prevalence Period" (which returns a Boolean).  the logic therein was adapted from the original "Prevalence Period" function, but modified to consider that these elements may be missing.  basically, if onset and abatement are present, they're the only things considered when evaluating whether the prevalence period is valid.  however, if either are missing, clinicalStatus is used as a surrogate to determine whether or not the Condition is currently happening (null, active, recurrence, or relapse).  "null" is considered valid in this context, because clinicalStatus is a modifier element, which means that IF it is present, then it must be considered - but if it is NOT present, then it doesn't need to be considered at all.  and because data coming from Epic so frequently lacks data, we had to make a determination about what a missing clinicalStatus means.  we decided to err on the side of presuming that if a Condition exists, but hasn't been explicitly marked "inactive" or "resolved," then it's presumed that the Condition is active.  in that case, if it's active and any presence of onset or abatement don't give reason to believe the Condition isn't (e.g., abatement is specified at some date in the past, or somehow onset is specified at some point in the future, which would be weird but possible), then there's no documented reason to believe the Condition isn't active and current, so it is allowed to pass.

hope this helps clear things up!

**Comment by aeyates** [comment]
@mattStorer Yes, I've reviewed the code changes for Prevalence Period and understand them. But that does not address this specific issue. Read the description again. For Encounter Diagnosis conditions of Hypertension (not other conditions, just Hypertension), we are no longer looking at prevalence period at all. This means that a person may be diagnosed with having hypertension if it was noted in an encounter several years ago and is actually marked resolved and abated. For example, this resource I've been using in testing results in the patient having a current diagnosis of Hypertension:

`{
  "resourceType": "Condition",
  "id": "condition-M-ResolvedCondition-2",
  "note": [
    {
      "text": "Indicates Diagnosis of Hypertension from an Encounter 10 years ago that is abated and resolved."
    }
  ],
  "category": [
    {
      "coding": [
        {
          "system": "http://terminology.hl7.org/CodeSystem/condition-category",
          "code": "encounter-diagnosis",
          "display": "Encounter Diagnosis"
        }
      ],
      "text": "Encounter Diagnosis"
    }
  ],
  "clinicalStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-clinical",
        "code": "resolved"
      }
    ]
  },
  "verificationStatus": {
    "coding": [
      {
        "system": "http://terminology.hl7.org/CodeSystem/condition-ver-status",
        "code": "confirmed"
      }
    ]
  },
  "code": {
    "coding": [
      {
        "system": "http://snomed.info/sct",
        "code": "59621000",
        "display": "Hypertension"
      }
    ],
    "text": "Hypertension"
  },
  "subject": {
    "reference": "Patient/M-ResolvedCondition"
  },
  "onsetDateTime": "2012-10-22",
  "abatementDateTime": "2012-11-15",
  "recordedDate": "2015-01-28T15:16:21-05:00"
}
`

**Comment by mattStorer** [comment]
ah, apologies, my misunderstanding.

you are referring to the lack of the "Is Valid Prevalence Period" reference in "Encounter Condition Indicating Preexisting Hypertension" below?

```
define "Condition Indicating Preexisting Hypertension":
  "Problem Condition Indicating Preexisting Hypertension" union 
  "Encounter Condition Indicating Preexisting Hypertension"

define "Problem Condition Indicating Preexisting Hypertension":
  "Problem Conditions" Condition
    where (TransformCodeableConcept(Condition.code) in "Hypertension" or TransformCodeableConcept(Condition.code) in
        "Non essential Hypertension SNOMEDCT") and "Is Valid Prevalence Period"(Condition)
	
define "Encounter Condition Indicating Preexisting Hypertension":
  "Encounter Conditions" Condition
    where (TransformCodeableConcept(Condition.code) in "Hypertension" or TransformCodeableConcept(Condition.code) in
        "Non essential Hypertension SNOMEDCT")
```

this change - splitting problem-list-item Conditions from encounter-diagnosis Conditions, and only considering prevalence period for problem-list-item ones - was made much earlier in a different commit.  I feel like I've got an email thread about it, but I can't get to it right now as it's in the email archive but the Outlook exchange server is down or some nonsense so I can't get to any of my old emails.  It was done for a reason though.

it may be the case that the recent fix to the Prevalence Period logic negates the earlier removal of Prevalence Period consideration from encounter-diagnosis Conditions (meaning that it may very well make sense to reintroduce that consideration).  I would want to check in with Michelle and / or Dave to see if they recall the precise reasoning for it, I'm sure I made that change as the result of a request to do so, even if the precise details of that request elude me at the moment.

**Comment by aeyates** [comment]
Yes, we should have a conversation with Michelle and Dave. I did put this information in my earlier email to everyone, but it was below the summary table and probably got missed. I would guess your other changes do negate the need for this. But if not, I just need a little context about the reasoning to properly document in the IG.

**Comment by aeyates** [comment]
We had more discussion via email on this change. For OHSU data at least, the point is moot, because encounter diagnosis conditions do not have associated dates and are never resolved. So while we could check for those things to exclude the condition, we would likely never encounter it. As Matt said, this was all motivated by the fact that many people with active Hypertension diagnoses were being excluded for lack of information - either dates or clinical status - and we wanted to err on the side of including them in those cases. We don't know what data at other institutions will look like, so it might be worth revisiting the stricter logic when we know for sure something is not active, but it's unlikely to make a difference.
